language: go
script: true
sudo: false

go:
  - 1.5
  - tip

before_install:
  - go get golang.org/x/lint/golint

install:
  - go get
  - go build

script:
  - go test ./...
  - $HOME/gopath/bin/golint ./...
